//TODO, MAKE CONFIG SYSTEM. FOR NOW THESE COMPILE TIME MACROS ARE FINE ENOUGH

#define PLAYER_COLOR Color::Green
#define SELECTION_STROKE_COLOR sf::Color::Blue
#define STROKE_SIZE 4
#define GAMEARRAYSIZE_MOCKUP 128
#define TILE_SIZE 32
#define FPS_COUNTER_UPDATE_TIME 0.5 //Seconds

#define ORGAN_HP_MAX 1000

#define SPAWN_TIME 1.0f

#define FRIENDLY_UNITS_PER_SPAWN 1
#define FRIENDLY_SPAWN_RANGE 100

#define ENEMY_UNITS_PER_SPAWN 1
#define ENEMY_SPAWN_RANGE 800

