//TODO, MAKE CONFIG SYSTEM. FOR NOW THESE COMPILE TIME MACROS ARE FINE ENOUGH

#define PLAYER_COLOR Color::Green
#define SELECTION_STROKE_COLOR sf::Color::Blue
#define STROKE_SIZE 4
#define GAMEARRAYSIZE_MOCKUP 128
#define TILE_SIZE 32
#define FPS_COUNTER_UPDATE_TIME 0.5 //Seconds